services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sinso\Variables\:
    resource: '../Classes/*'

  Sinso\Variables\Hooks\ContentProcessor  :
    tags:
      - name: event.listener
        identifier: 'my-package/content-modifier'
